// frontend/src/lib/components/TopUsers.svelte
<script lang="ts">
  let { users } = $props<{ users: any[] }>();
</script>

<div class="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
  <h2 class="text-2xl font-bold mb-4 text-gray-900 dark:text-white">
    Top Users by Followers
  </h2>
  <div class="space-y-3">
    {#each users as user, i}
      <div class="flex items-center justify-between p-3 bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-gray-700 dark:to-gray-600 rounded-lg hover:shadow-md transition-shadow">
        <div class="flex items-center space-x-3">
          <div class="flex-shrink-0 w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold">
            {i + 1}
          </div>
          <div>
            <p class="font-semibold text-gray-900 dark:text-white">
              {user.displayName || user.handle}
            </p>
            <p class="text-sm text-gray-600 dark:text-gray-400">
              @{user.handle}
            </p>
          </div>
        </div>
        <div class="text-right">
          <p class="font-bold text-blue-600 dark:text-blue-400">
            {user.followersCount?.toLocaleString() || 0}
          </p>
          <p class="text-xs text-gray-500 dark:text-gray-400">
            followers
          </p>
        </div>
      </div>
    {/each}
  </div>
</div>

// frontend-nextjs/app/bluefacts/top-users/page.tsx
'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { DashboardHeader } from '@/components/DashboardHeader';
import Link from 'next/link';

const API_BASE = 'http://100.69.129.86:3003';

export default function TopUsers() {
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      const response = await fetch(`${API_BASE}/api/most-followed?limit=100`);
      const result = await response.json();
      setUsers(result.data);
    } catch (error) {
      console.error('Failed to fetch users:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-zinc-950 dark:to-zinc-900">
      <div className="container mx-auto px-4 py-8">
        <DashboardHeader />

        <div className="mb-8">
          <div className="flex items-center space-x-4 mb-4">
            <Link href="/bluefacts" className="text-blue-600 dark:text-blue-400 hover:underline">
              ← Back to BlueFacts
            </Link>
          </div>
          <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100 mb-2">
            🌟 Most Popular Users on Bluesky
          </h1>
          <p className="text-slate-600 dark:text-slate-400">
            Top 100 users with the most followers on Bluesky, updated daily
          </p>
        </div>

        {loading ? (
          <div className="flex items-center justify-center py-20">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500"></div>
          </div>
        ) : (
          <div className="bg-white dark:bg-zinc-800 rounded-lg shadow-lg border border-slate-200 dark:border-zinc-700">
            <div className="p-6">
              <div className="grid gap-4">
                {users.map((user: any, index) => (
                  <motion.div
                    key={user.did}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="flex items-center justify-between p-4 bg-slate-50 dark:bg-zinc-700 rounded-lg hover:bg-slate-100 dark:hover:bg-zinc-600 transition-colors"
                  >
                    <div className="flex items-center space-x-4">
                      <div className="flex-shrink-0 w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold">
                        #{index + 1}
                      </div>
                      {user.avatar && (
                        <img 
                          src={user.avatar} 
                          alt={user.display_name || user.handle}
                          className="w-12 h-12 rounded-full"
                        />
                      )}
                      <div>
                        <h3 className="font-semibold text-slate-900 dark:text-slate-100">
                          {user.display_name || user.handle}
                        </h3>
                        <p className="text-slate-500 dark:text-slate-400">@{user.handle}</p>
                        {user.description && (
                          <p className="text-sm text-slate-600 dark:text-slate-300 mt-1 line-clamp-2">
                            {user.description}
                          </p>
                        )}
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="text-2xl font-bold text-blue-600 dark:text-blue-400">
                        {user.followers_count.toLocaleString()}
                      </div>
                      <div className="text-sm text-slate-500 dark:text-slate-400">followers</div>
                      <div className="text-xs text-slate-400 dark:text-slate-500 mt-1">
                        {user.following_count.toLocaleString()} following • {user.posts_count.toLocaleString()} posts
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
